import os
from dotenv import load_dotenv

load_dotenv()

DB_PATH = "portfolio.db"

STARTING_CAPITAL = 100000
MIN_TICKERS = 3
MAX_TICKERS = 7
MAX_ASSET_WEIGHT = 0.40

HISTORY_DAYS = 180
MARKET_BENCHMARK = "SPY"
BAR_TIMEFRAME = "1Day"

RISK_FREE_RATE = 0.02
VAR_CONFIDENCE = 0.05
TRADING_DAYS = 252
ROUND_DECIMALS = 4

MOMENTUM_LOOKBACK_SHORT = 30
MOMENTUM_LOOKBACK_MEDIUM = 60
MOMENTUM_LOOKBACK_LONG = 90
TOP_N_SELECTION = 5

DEFAULT_STRATEGY_MODE = "manual"
DEFAULT_WEIGHTING_METHOD = "equal"

ALPACA_API_KEY = os.getenv("ALPACA_API_KEY")
ALPACA_API_SECRET = os.getenv("ALPACA_API_SECRET")
ALPACA_DATA_FEED = "iex"